### ISSUE TITLE
Events 30 days

### ISSUE THREAD

**Issue by lnsiqueira** [microsoftgraph/msgraph-sample-aspnet-core#45]
Hi,

Is it possible for me to catch the events of a period longer than 7 days?

Thank you.
Luciano

**Comment by jasonjoh** [comment]
Hi @lnsiqueira thanks for your interest in Microsoft Graph! This isn't really the best place to ask general questions like this, but yes, you can extend the period by adjusting the start or end values passed to the calendar view API.
